version: '3.9'

services:
 web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  restart: always
  volumes:
   - .:/code
  ports:
   - "8000:8000"
  environment:
   - DJANGO_SETTINGS=django_project.settings
  depends_on:
   - db


 db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
 postgres_data: